# Generated by Django 6.0.2 on 2026-02-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this project as featured on the homepage'),
        ),
    ]
