# Generated by Django 6.0.2 on 2026-06-04 05:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectpage_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text shown at the top of the projects page.'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Detailed description of the project.'),
        ),
    ]
