# Generated by Django 5.2.17 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectindexpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='gh_description',
            field=models.TextField(blank=True, editable=False, help_text='Auto-filled from GitHub'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gh_forks',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-filled from GitHub'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gh_full_name',
            field=models.CharField(blank=True, editable=False, help_text='Auto-filled from GitHub (e.g. owner/repo)', max_length=255),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gh_language',
            field=models.CharField(blank=True, editable=False, help_text='Primary language detected by GitHub', max_length=50),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gh_last_updated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Last push date from GitHub', null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gh_stars',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-filled from GitHub'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to the GitHub repository. Stats are fetched automatically.'),
        ),
    ]
