services:
  blog-backend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: blog-backend
      restart: unless-stopped
      ports:
        - 8000:8000
      environment: &backend-variable
        POSTGRES_SERVER: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: supersecretpassword
        POSTGRES_DB: chithi

      networks:
            - proxy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.blog-backend.rule=Host(`blog.zad.bd`)"
        - "traefik.http.routers.blog-backend.entrypoints=websecure"
        - "traefik.http.routers.blog-backend.tls=true"
        - "traefik.http.routers.blog-backend.tls.certresolver=letsencrypt"
        - "traefik.http.services.blog-backend.loadbalancer.server.port=8000"


networks:
  proxy:
    external: true