services:
  backend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: blog-backend
      restart: unless-stopped
      environment: &backend-variable
        POSTGRES_SERVER: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: supersecretpassword
        POSTGRES_DB: chithi

      networks:
            - proxy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`blog.zad.bd`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"


networks:
  proxy:
    external: true