[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.1.1",
    "django-vite>=3.1.0",
    "psycopg[binary]>=3.3.2",
    "readtime>=3.0.0",
    "uvicorn>=0.40.0",
    "wagtail>=7.3",
    "wagtailcodeblock>=1.30.0.0",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = ["django-debug-toolbar>=6.2.0", "djhtml>=3.0.10"]
