# Generated by Django 6.0.2 on 2026-02-17 08:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_text',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_text',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Building things with Code & Passion', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_posts_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
