# Generated by Django 6.0.2 on 2026-02-17 09:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_cta_primary_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_primary_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_secondary_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 64, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1)]], {})}),
        ),
    ]
