# Generated by Django 6.0.2 on 2026-06-04 05:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_hero_cta_primary_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_ctas',
            field=wagtail.fields.StreamField([('cta', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button label text.', 'max_length': 64, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Destination URL for this button.', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1)]], {})}, help_text='Call-to-action buttons in the hero section.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Supporting text below the hero title.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Building things with Code & Passion', help_text='Main heading displayed in the hero section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='latest_posts_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of recent blog posts to display on the homepage.'),
        ),
    ]
