# Generated by Django 6.0.2 on 2026-06-04 10:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('aos_heading', 4), ('aos_quote', 7), ('aos_highlight', 9), ('aos_separator', 11), ('aos_image', 14), ('aos_callout', 16), ('aos_stats_grid', 21), ('aos_card_grid', 25)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fade-up', 'Fade up'), ('fade-down', 'Fade down'), ('fade-right', 'Fade right'), ('fade-left', 'Fade left'), ('zoom-in', 'Zoom in'), ('zoom-in-up', 'Zoom in up'), ('zoom-in-down', 'Zoom in down'), ('flip-up', 'Flip up'), ('slide-up', 'Slide up')], 'help_text': 'Scroll animation effect.'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0', 'None'), ('100', '100ms'), ('200', '200ms'), ('300', '300ms'), ('400', '400ms'), ('500', '500ms')], 'help_text': 'Animation delay.'}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 4: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('text', 2), ('level', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional attribution.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('quote', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('primary', 'Primary'), ('accent', 'Accent')], 'help_text': 'Color variant.'}), 9: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('text', 5), ('variant', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('line', 'Line'), ('dots', 'Dots'), ('space', 'Space')]}), 11: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('style', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('image', 12), ('caption', 13)]], {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], 'help_text': 'Callout style variant.'}), 16: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('title', 2), ('body', 5), ('variant', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Number or short value.', 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Label below the value.', 'required': True}), 19: ('wagtail.blocks.StructBlock', [[('value', 17), ('label', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'max_num': 6, 'min_num': 1}), 21: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('stats', 20)]], {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('code', 'Code'), ('lightning-bolt', 'Lightning'), ('shield', 'Shield'), ('chart-bar', 'Chart'), ('globe', 'Globe'), ('puzzle-piece', 'Puzzle')], 'help_text': 'Icon for this card.'}), 23: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 5), ('icon', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'max_num': 6, 'min_num': 1}), 25: ('wagtail.blocks.StructBlock', [[('animation', 0), ('delay', 1), ('cards', 24)]], {})}, help_text='Animated content blocks for the homepage.'),
        ),
    ]
