# Generated by Django 6.0.2 on 2026-06-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='mood',
            field=models.CharField(choices=[('tech', 'Technology'), ('personal', 'Personal'), ('politics', 'Politics'), ('tutorial', 'Tutorial'), ('opinion', 'Opinion'), ('announcement', 'Announcement'), ('research', 'Research'), ('review', 'Review')], default='tech', help_text='The mood/category of this post — shown as a colored badge.', max_length=32),
        ),
    ]
