# Generated by Django 6.0.2 on 2026-02-20 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='site_copyright_from',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='site_copyright_to',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2026), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
