# Generated by Django 6.0.2 on 2026-02-20 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0002_alter_siteconfigsettings_site_copyright_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfigsettings",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("all_rights", "All Rights Reserved"),
                    ("mit", "MIT License"),
                    ("cc_by", "Creative Commons BY"),
                    ("cc_by_sa", "Creative Commons BY-SA"),
                    ("gpl_3", "GNU GPL v3"),
                    ("other", "Other / Custom"),
                ],
                default="all_rights",
                help_text="The legal license governing the site's content.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfigsettings",
            name="site_copyright_from",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="siteconfigsettings",
            name="site_copyright_to",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
    ]
