# Generated by Django 6.0.2 on 2026-02-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_siteconfigsettings_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='license_type',
            field=models.CharField(choices=[('all_rights', 'All Rights Reserved'), ('mit', 'MIT License'), ('cc_by', 'Creative Commons BY'), ('cc_by_sa', 'Creative Commons BY-SA'), ('gpl_3', 'GNU GPL v3')], help_text="The legal license governing the site's content.", max_length=20, null=True),
        ),
    ]
