# Generated by Django 6.0.2 on 2026-06-04 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_siteconfigsettings_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='site_copyright_from',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Starting year for the copyright notice.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='site_copyright_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ending year for the copyright notice.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='site_name',
            field=models.CharField(help_text='Display name of the site.', max_length=32),
        ),
    ]
