# Generated by Django 6.0.7 on 2026-08-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_alter_siteconfigsettings_site_copyright_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='license_type',
            field=models.CharField(choices=[('all_rights', 'All Rights Reserved'), ('mit', 'MIT License'), ('apache_2_0', 'Apache License 2.0'), ('gpl_3', 'GNU GPL v3'), ('bsd_3_clause', 'BSD 3-Clause'), ('cc_by', 'CC BY 4.0'), ('cc_by_sa', 'CC BY-SA 4.0'), ('cc_by_nc', 'CC BY-NC 4.0'), ('cc0', 'CC0 1.0'), ('public_domain', 'Public Domain')], help_text="The legal license governing the site's content.", max_length=20, null=True),
        ),
    ]
