# Generated by Django 5.2.17 on 2026-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_siteconfigsettings_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
