# Generated by Django 5.2.17 on 2026-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_siteconfigsettings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
