# Generated by Django 5.2.17 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_alter_siteconfigsettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigsettings',
            name='github_token',
            field=models.CharField(blank=True, help_text='Personal Access Token for GitHub API rate limit (1000 req/hr vs 60). Generate at https://github.com/settings/tokens. No scopes needed for public repo data.', max_length=255),
        ),
    ]
